services:
  db:
    image: postgres:15-alpine
    container_name: logistics_db
    environment:
      POSTGRES_DB: logistics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: logistics_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logistics_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Use the same secret as in application.properties for consistency
      JWT_SECRET: hngmsUSryRKee4tb747bbzyjU85UihPRScLHWyWASzI=
      JWT_EXPIRATION: 3600000 # 1 hour in milliseconds
    depends_on:
      db:
        condition: service_healthy # Ensure DB is healthy before starting app

volumes:
  pg_data: